### ISSUE TITLE
Why is it possible to set a key/value pair in a string?

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#111]
This code
```
var s = "xxx"; // s is a string
s["abc"] = "xyz"; // WHY doesn't this line fail?
print("s="+s);
print(s["abc"]); // this is undefiled, despite the above line succeeding
```
allows to associate "abc" key with the "xyz" value without an error.
Why doesn't the second line fail?
s is a string, ```s["abc"]``` can't be retrieved afterwards. Shouldn't setting the key/value pair be disallowed?

If the first line is replaced with ```var s = []; ``` - setting the key/value pair succeeds and s becomes an object after this. Not sure if this behavior is correct.

**Comment by ccxvii** [comment]
This is as expected by the JS language. As a language JS has a lot of oddities and quirks. This is one of them.

Accessing a property on a value will do the ToObject primitive operation. For string values, this creates a new temporary String class object wrapping the value. Thus, s["abc"] creates a temporary String class object which is never seen again, since nothing in your code above saves it.

The code above will create two temporary string objects; once for the assignment, and a new one for the access in the print statement.
