### ISSUE TITLE
Please support shebanging

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#117]
When the first line of script begins with ```#!``` it should ignore it, at least optionally if strict adherence to the standard is a concern.

This would enable the use of JavaScript from the command line utilities with
```
#!/usr/local/bin/mujs

print("Hello World!");
```

NodeJS apparently has such feature for the same reason: https://stackoverflow.com/questions/10696222/make-node-js-support-the-shebang-for-javascript-files

**Comment by gardhr** [comment]
As a workaround, maybe just preprocess the script before it gets passed to mujs. That won't help if you're using the script loader of course. Anyway I was able to fix it with just a few lines of JS. Shouldn't be much harder from C either.

**Comment by sgbeal** [comment]
FWIW, implementing this simply requires *ignoring* the *first* (and only the first) line of the first (and only the first) file read by the interpreter if it starts with '#'. The actual "shebang logic" is handled by the OS. Usability or internal API structure might dictate ignoring such initial lines of all files, rather than just the first, but pedantic correctness suggests that it should only be ignored in the first filename passed to the interpreter by the client app.

**Comment by yurivict** [comment]
> maybe just preprocess the script before it gets passed to mujs?

This is impossible when it is installed into a read-only location.
