### ISSUE TITLE
Array.sort method doesn't work when sort function is specified

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#122]
This code:
```
var l = [{a: 0.5}, {a: -0.1}, {a: 0.7}];
l.sort(function(x,y) {return x.a - y.a;});
print(JSON.stringify(l));
```
prints still unsorted elements:
```
[{"a":0.5},{"a":-0.1},{"a":0.7}]
```

**Comment by isRyven** [comment]
The reason is pretty simple, mujs internally uses `qsort` to perform sorting, and `qsort` essentially expects integer value to be returned from its callback, in your case, when you return a subtract result, it will be coerced to 0, so no sorting is done. To overcome this, manually return -1, 0 or 1.

```js
l.sort(function(x, y) { return (x.a === y.a) ? 0: (x.a > y.a) ? 1 : -1; });
```

**Comment by yurivict** [comment]
Thanks for troubleshooting this. I see.

The same code run with ```node``` returns the correct result (when ```print``` is replaced with ```console.log```):
```
$ node sort.js 
[{"a":-0.1},{"a":0.5},{"a":0.7}]
```

I think MuJS should do the same.

**Comment by sgbeal** [comment]
Firefox also handles this using floating-point comparison of the results, rather than integers, and presumably it is following the spec. C's `qsort()` uses integers but does not do the sorting itself: it uses a comparison function which may internally use whatever comparison it likes, including floating-point.

It seems that my own scripting engine gets this wrong in the same way (and presumably for the same reason) muJS does (but i'm mine's not confined by a formal spec ;)).

**Comment by isRyven** [comment]
i'll do a pr for a quick fix

**Comment by sgbeal** [comment]
FWIW, here's a fix for my owns scripting engine which very probably looks quite close to what muJS will need (but i'm not familiar with muJS's internals):

https://fossil.wanderinghorse.net/r/cwal/info/4f0d98c3294778c6

**Comment by avih** [comment]
It seems to be a mujs bug. The ES5.1 spec says:

> If `comparefn` is not undefined, it should be a function that accepts two arguments x and y and returns a negative value if x < y, zero if x = y, or a positive value if x > y.

**Comment by isRyven** [comment]
Well, based on spec quote this clearly is not mujs bug. It defines rules for the sort callback function, and clearly we are just trying to use it incorrectly.

**Comment by yurivict** [comment]
No, based on this quote from the standard this is clearly a bug in MuJS, because it talks about "negative value" and "positive value" expectation, and MuJS first rounds it to the integer which it shouldn't do.

**Comment by isRyven** [comment]
Good point.
