### ISSUE TITLE
Is it possible to increase the default stack size?

### ISSUE THREAD

**Issue by ahaoboy** [ccxvii/mujs#182]
With the increase in hardware performance and the widespread use of TypeScript, in scenarios where code is written in TypeScript and transpiled to ES5, some larger projects may encounter stack overflow issues, for example: https://github.com/mpv-player/mpv/issues/13131

**Comment by ahaoboy** [comment]
The configuration of Regex also needs to be increased. For example, in PrismJS, many complex Regex are used, and the default REG_MAXCLASS is too small.

**Comment by avih** [comment]
Quoting myself from that referenced mpv issue:

> Specifically, the mujs stack has a fixed size because it cannot be easly relocated (realloc-ed) due to some other implementation details which may keep reference to some specific stack values, which cannot be freed (e.g. by realloc). IIRC specifically short strings only.
>
> However, with some effort (enhancing mujs), the stack can be made non-fixed, by keeping past-stacks (before allocating a bigger stack) in memory (not-freed) until the VM is finalized.

IIRC I had  POC which worked well (instead of stack overflow, allocate double the stack size, copy the existing stack into it, and keep the past stack[s] in a linked list to be freed on finalization so that short string references remain valid), but I don't know where's this code now.

Might be worth also considering removing other hard limits, such as env sizes and regexp length, to be dependent only on system memory availability (or some runtime-configurable limit to impose some artificial limit before things blow up, but without pre-allocating the whole space for this mazimum limit).

**Comment by ahaoboy** [comment]
Is there any other way to set these default config values? For applications that use package managers like apt or pacman to install mujs, these configurations cannot be modified and can only be integrated through source code. This leads to a significant amount of noisy code.

**Comment by avih** [comment]
> MuJS was written to be trivial to configure and include in your build system (build `one.c` with whatever options you like, link it in, and you're good to go).

This requires maintenance by the client project instead of the distro doing the maintenance, and it's generally highly inconvenient, and typically not required because so far it's been backward compatible, maybe except for some rare cases long time ago.

Also, vendoring a copy is a lot more likely to happen in projects which target an embedded or other specialized environments, where tweaking these limits to the respective optimum is much more likely to happen anyway.

However, as a system library, which typically builds the default config/limits, it's much more likely to be less sensitive to such limits in term of memory usage, especially, as I noted, when these fixed arrays typically have a very small part in defining the overall memory usage of a script, or even of a bare VM.

Therefore, my suggestion is to raise the defaults meaningfully so that it can be used as a system lib (as many distros provide it), where projects which actually care about the limits can still tweak them to their liking.

**Comment by Kagami** [comment]
> The configuration of Regex also needs to be increased. For example, in PrismJS, many complex Regex are used, and the default REG_MAXCLASS is too small.

I've encountered that issue too with regexp taken from a real project:

```
> ''.match(/%t([aAbBcCdDeFgGhHIjmMnprRStTuUVwWxXyYzZ])/)
SyntaxError: regular expression: too many character class ranges
	at [stdin]:1
```

**Comment by ccxvii** [comment]
I can increase the default sizes, so if you could figure out and let me know the breaking points where your TypeScript workflows to run out of stack -- and also whether it's only stack, or also lexical closure nesting (ENVLIMIT) and try/catch nesting depth (TRYLIMIT) that cause issues.

I want accurate numbers for where limits cause things to start to fail, so I can judge how much safety margin to add now to compensate for future bloat, so we don't have to update the defaults again in a month or two.

**Comment by ahaoboy** [comment]
I currently cannot provide specific numbers, but the current configuration cannot support medium to large projects. I will attempt to find the smallest reproducible demo and then use it as a baseline for measurements. Perhaps, this approach can lead to a more suitable configuration.

**Comment by ahaoboy** [comment]
I may have found the issue: recursion depth limitation. I am using mujs to run React, and since both tsx and layout calculations are implemented recursively, when calculating the layout in nodes with deep element nesting, it exceeds the maximum recursion depth.

I tested the recursion depth of some JavaScript engines, and mujs has the smallest one. I recommend expanding the JS_STACKSIZE and other settings to four times the original values. This should approximate the level of Boa, and it should be sufficient for the majority of requirements.
```js
function f(deep) {
  console.log(deep)
  f(deep + 1)
}

f(0)

// mujs
// 61
// stack overflow

// qjs
// 337
// InternalError: stack overflow

// node
// 11289
// node: internal / util / inspect: 764

// deno
// 10590
// error: Uncaught RangeError: Maximum call stack size exceeded

// boa
// 289
// thread 'main' has overflowed its stack

// mujs JS_STACKSIZE 1024
// 253
// stack overflow
```

I'm not sure if expanding these settings will consume too much memory during mujs startup, causing errors on some embedded devices. Increasing only JS_STACKSIZE seems to be the only solution for my issue. After feasibility verification, I might consider switching to other engines like qjs.

**Comment by ahaoboy** [comment]
There may be some parse settings that need to be modified as well, for example, when using tools like webpack for bundling ts to js, it may generate very large arrays or objects, leading to parsing failures.
https://github.com/mpv-player/mpv/issues/13131

**Comment by avih** [comment]
> I tested the recursion depth of some JavaScript engines, and mujs has the smallest one. I recommend expanding the JS_STACKSIZE and other settings to four times the original values.

The goals of this issue are two:
1. Understanding practical required minimum limits. This means actual, real-world, use cases (the more the better), and for each understand which values of JS_STACKSIZE, JS_ENVLIMIT, JS_TRYLIMIT, JS_ASTLIMIT (and possibly the regexp limits) are sufficient to operate correcty.
2. From these known limits of the use cases, decide which actual limits to use, which leave some headroom so that we don't have to raise the limits again tomorrow.

The comparison of stack depth in one specific trivial and non-practical case has some value, but not much, because it really doesn't represent real-world use cases.

So do you have such examples where you know what the minimum limits are?

**Comment by ahaoboy** [comment]
> So do you have such examples where you know what the minimum limits are?

This demo overflows when clicking increase and decrease. However, the version with mujs settings adjusted locally runs normally, meaning that the auto-increment per second and the increase and decrease buttons all work correctly.
https://github.com/ahaoboy/mpv-easy-demo/blob/main/src/counter-redux.tsx

```tsx
// import Element from "./counter-ui"
import Element from "./counter-redux"
```

**Comment by ahaoboy** [comment]
I've found something interesting: variables in a recursive function changes the recursion depth.
```js
function render(deep) {
  console.log('render', deep)
  render(deep + 1)
}


render(0)

// render 61
// stack overflow
```

```js
function render(deep) {
  console.log('render', deep)
  var a = 1
  render(deep + 1)
}


render(0)

// render 48
// stack overflow
```


```js
function render(deep) {
  console.log('render', deep)
  var a = 1
  var b = 1
  render(deep + 1)
}


render(0)

// render 40
// stack overflow
```

```js
function render(deep) {
  console.log('render', deep)
  var a = function () { };
  render(deep + 1)
}


render(0)

// render 123
// stack overflow
```

```js
function render(deep) {
  console.log('render', deep)
  var a = 1
  var b = 1
  var c = 2
  var f = function () {

  }
  render(deep + 1)
}


render(0)

// render 123
// stack overflow
```
I think that's the issue, the more variables in a recursive function, the easier it is to exhaust the stack. However, declaring functions in a recursive function can reset or reduce the stack.

**Comment by avih** [comment]
> variables in a recursive function changes the recursion depth.

Of course. Variables take space at the stack, at each of the recursive instances, and i's far from the only "interesting" fact you might figure out.

This is why we need real world cases and not synthetic trivial test cases.

> However, the version with mujs settings adjusted locally runs normally

Did you need to raise all of JS_STACKSIZE, JS_ENVLIMIT, JS_TRYLIMIT, JS_ASTLIMIT (and possibly the regexp limits) for this to run correctly? or was it enough only to raise one or few?

What's the minimum number values of the above limits which were enough to run this demo?

Do you have use cases other than this demo?

This is what we need, e.g. for test case whatever with whatever buttons, JS_STACKSIZE needs minimum of 400, and JS_TRYLIMIT should be at least 200.

Once we know the real minimum numbers for real world cases, we'll figure out how to change the defaults in mujs so that it covers the known cases and probably at least twice more for future cases.

But we need to have real numbers. Presumably you have some real projects you tried which needed the limits raised, so we need the real minimum numbers...

**Comment by ahaoboy** [comment]
> Of course. Variables take space at the stack, at each of the recursive instances, and i's far from the only "interesting" fact you might figure out. 

However, the consumption of mujs is too high, with one variable decreasing from 61 to 48. In contrast, for qjs, a variable only decreases from 331 to 330.

I only adjusted the JS_STACKSIZE to 1024, and my code works fine now. There are no other cases

**Comment by avih** [comment]
> I only adjusted the JS_STACKSIZE to 1024, and my code works fine now. There are no other cases

But in [this comment](https://github.com/mpv-player/mpv/issues/13131#issuecomment-1895291564), you also show JS_ENVLIMIT raised from 128 to 512, JS_TRYLIMIT raised from 64 to 128,

So you're saying that these additional changes are not required to run whatever you were trying to run?

> Due to mujs limitations, it is currently not possible to incorporate libraries that heavily rely on Proxy, as the stack size is set too small. This limitation also causes stack overflow when using dependencies like Redux.

So does raising JS_STACKSIZE to 1024, and nothing more, enough to "incorporate libraries that heavily rely on Proxy" and "using dependencies like Redux"?

**Comment by ahaoboy** [comment]
> So does raising JS_STACKSIZE to 1024, and nothing more, enough to "incorporate libraries that heavily rely on Proxy" and "using dependencies like Redux"?


I recompiled once, only modifying the following:

```c
#define JS_STACKSIZE 1024	/* value stack size */
```
My Redux demo can now run. This is because in React, rendering and layout are mostly implemented using recursion, making it prone to stack overflow. However, Proxy cannot be polyfilled, and if you want to use Proxy, you must use an ES6 JavaScript engine.

**Comment by ccxvii** [comment]
Thanks. I'm preparing a patch to increase stack size and parse recursion limits.

Proxy is not polyfillable from pure Javascript, but you can use the C interface to add more advanced language features like these by making use of the "userdata" extension capability.

See the "extensions" branch for an example of a TypedArray implementation.

**Comment by ahaoboy** [comment]
If someone encounters this stack overflow problem, you can try using the Babel plugin to add a function variable declaration at the beginning of all functions. For examples: https://github.com/ahaoboy/mpv-easy-demo/blob/main/babel/hack.js


> Of course. Variables take space at the stack, at each of the recursive instances, and i's far from the only "interesting" fact you might figure out. 

The interesting thing is that if the declared variable is a function, the stack will be reset(maybe?). Now, we can play the Snake game in mpv using React.

![snake](https://github.com/ahaoboy/mpv-easy-demo/blob/main/img/snake.gif?raw=true)
