### ISSUE TITLE
tailcall optimization & coroutines

### ISSUE THREAD

**Issue by katlogic** [ccxvii/mujs#32]
Yay or nay?

Poking around the codebase I noticed it is modeled after Lua (sans register VM) in many regards and it might be worth it to continue in this trend.

I do realize this is basically introducing bloat and non-standard extension, however the two $SUBJ features are the key selling points of Lua - and will be missed by anybody who ports Lua scripting to use mujs. Some might also consider these two making js suck (vastly) less.

Question is, would be code submissions of this sort considered or are they better kept in side fork as the goal of mujs is to be strictly minimal ecma implementation, with no compromises made which would introduce nonstandard features?

Regarding technicalities, superficially it seems that no big refactoring would be necessary and all the changes would be quite self contained, with the exception js_State->{stack,top,bot} which would have to go into new js_Thread (and original references to js_State should be made via js_Thread->J)

Tailcall optimization would be enabled by scope flag (as it is a nonstandard semantic).

Coroutines as a package call, very similiar to Lua, including unability to yield across C stack. As a side benefit, ES6 generators could be then done simply by adding syntactic sugar to this.

**Comment by ccxvii** [comment]
Tailcall optimization would not be difficult to add; the only real "drawback" of doing it is losing stack trace information for exceptions and runtime errors; the benefit is allowing naturally recursive functional code to work without worrying about running out of stack.

Coroutines would be useful, but are a bit counter to the original idea of a minimal JS interpreter.
An implementation would still be fairly minimal in terms of resulting code size; but it does involve a much larger effort of implementation.

Note however, that any significant contributions of code to MuJS will need a copyright assignment to Artifex since we dual license the code as part of commercial licensing of MuPDF, which is what funds the development of both MuPDF and MuJS.

**Comment by ccxvii** [comment]
In summary: Yay, to both proposals. But I've got limited time to work on it myself (I have more urgent projects I need to focus on in the short term), and any contributions will need copyright assignment if they are to be merged into the official mujs project.

**Comment by katlogic** [comment]
> copyright assignment

Fine by me, as long it's not something obtuse like faxing stuff around.

I'll start with the tailcall following week or so.
