### ISSUE TITLE
Doubt about how to implement my code

### ISSUE THREAD

**Issue by AsierRF** [ccxvii/mujs#34]
Hello,
I am trying to develop a simple code that runs a javascript function that gets two int values as input and returns the sum of those int values. Simple. I am trying to follow the documentation and I have the following code:
```
#include <stdio.h>
#include <mujs.h>

int main(int argc, char **argv)
{
        double ret = 0;
        js_State *J = js_newstate(NULL, NULL, JS_STRICT);
        //Push the function
        js_loadstring(J, "myfun", "function myFunction(p1, p2) { return p1+p2; }");
        //js_getglobal(J, "myfun");
        //Push the "this" value
        js_pushglobal(J);
        //Push the variables
        js_pushnumber(J,2);
        js_pushnumber(J,3);
        //Call the function
        js_call(J,2);
        ret = js_tonumber(J, -1);
        printf("The sum is: %lf", ret);
        js_freestate(J);
}
```

As you can imagine, this does not work, I followed the steps in the reference page:

> To call a function, you must use the following protocol: 1) push the function to call onto the stack, 2) push the this value to be used by the function, 3) push the arguments to the function in order, 4) finally, call js_call with the number of arguments pushed in step 3.

However, I am confused about what is the "filename" value in the "js_loadstring" function? I understand it gets the JavaScript value from the "source" variable (the 3rd variable given as input).

In addition, I would like to get the value returned by the javascript code in the C program.

Thanks for your time. Any suggestion will be welcome :)

**Comment by avih** [comment]
`js_loadfile` gets a file name and compiles (parses) the file's content - it does not yet run it.

`js_loadstring` is the same, but you're providing the content of the file as the other argument. I.e. the vm thinks it loads a file with some name (for stack traces), but it never actually touches the disk, and takes your string as its content instead.

On both cases, after parsing, you need to also run it to actually apply the code (which in your case will end up with a global function `myFunction`).

So right after your `js_loadstring`, you need to "call" the parsed content to also run it, and you call it like you call anything else in mujs - push a this value, e.g. `js_pushglobal(J);` and `js_call(J, 0);` (no arguments).

The rest of your code should now work.

Alternatively, you can shorten this triplet (parse content, push this, call it to run it) to one command: `js_dostring(J, <content-string>)`, which you can use instead of your `js_loadstring`, and it should work.

**Comment by AsierRF** [comment]
First of all, thanks for your help.

The code right now prints "Nan" as result.

I am afraid I did not understand how I can do this that you mention:

> So right after your js_loadstring, you need to "call" the parsed content to also run it, and you call it like you call anything else in mujs

Based on the reference page, the function `js_loadstring` already pushes the function after compiling. And I can't find any function in the reference page that is used to push the functions.

An extra question related to `js_dostring`. Can I also set the input variables and get the return values if I use `js_dostring`?

**Comment by ccxvii** [comment]
A few misconceptions that need to be cleared up.

js_loadstring pushes an anonymous function that when run executes the code in the string. In your example, the function created by js_loadstring will define *another* function called myFunction when it is run.

The "this" value you need to push when calling a function is the value that 'this' will be bound to when executing the function. If you don't know or understand what this means, just use js_pushundefined.

js_newstate(NULL, NULL, JS_STRICT);
js_loadstring(J, "myfun", "function myFunction(p1, p2) { return p1+p2; }");
js_pushundefined(J); /* we don't have a 'this' object */
js_call(J, 0); /* execute the script function that defines myFunction */

Now we have run the code that defines myFunction. Now you can use it, like so:

js_getglobal(J, "myFunction"); /* get the myFunction object */
js_pushundefined(J;) /* no this binding here either */
js_pushnumber(J, 2); /* argument 1 */
js_pushnumber(J, 3); /* argument 2 */
js_call(J, 2); /* call with 2 arguments */
ret = js_tonumber(J, -1); /* read return value */
js_pop(J, 1); /* pop return value to clean up stack */

**Comment by AsierRF** [comment]
Thanks a lot for your help.
The code works fine and now I understand the process.
I would suggest you add this or a similar example to the "Examples" page. I think it would help people understand it better.
