### ISSUE TITLE
Incorrect Results for {}+[];  {}+"";

### ISSUE THREAD

**Issue by JitCompiler** [ccxvii/mujs#50]
Some test results:
>> {}+[]
>0
>> {}+""
>0
>> ""+{}
>[object Object]

But in Firefox and Chrome result of {}+[] and  {}+"" are both [object Object]
My understanding is that when any 1 of the operands of a + is an object, both operands are converted to string using .toString(). For an empty object {}, the default .toString() is called which returns the string "object Object". An empty array [] is converted to an empty string. The + is then considered as a string concatenation yielding "[object Object]".

**Comment by ccxvii** [comment]
For some unknown to me yet reason it is parsing "{}+[]" as "+[]". I'll need to investigate; it may be something weird in the parser or compiler that is treating the {} as an empty statement rather than an object as it should.

**Comment by ccxvii** [comment]
It is parsing {}+[] as an empty block followed by an expression statement with a unary plus on an array initializer. See section 12.4 in the ECMA-262-5.1 reference. An expression statement cannot start with an opening curly brace because that would make it ambiguous with a block.

Thus, Firefox and Chrome treating {}+[] as object+array concatenation is not according to spec. I believe they have a hardcoded special case for coping with empty object initializers (as this could be a common user error). If you make the concatenation using non-empty objects it will match behavior with MuJS and parse them as blocks, not object initializers.

js> {a:5}+[]
0

js>{a:5,b:6}+[]
typein:2:6 SyntaxError: missing ; before statement:
typein:2:6 {a:5,b:6}+[]
