### ISSUE TITLE
Unable to convert undefined to object

### ISSUE THREAD

**Issue by dkoreshkov** [ccxvii/mujs#62]
Hello,
I fire up mujs and type this:
print(this.foo || print)
The result is function print () { ... }, which looks correct.

Now I pipe the same into stdin:
echo 'print(this.foo || print)' | ./mujs
The result is:
TypeError: cannot convert undefined to object
        at [string]:1

I was able to fix this by changing js_pushundefined() to js_pushglobal() in js_dostring() and js_dofile().
Is that the solution?

**Comment by ccxvii** [comment]
Actually, the fix is changing eval_print to call js_pushundefined rather than js_pushglobal.

The interpreter is running in strict mode by default, where 'this' in a global context is undefined (and undefined 'this' is not promoted to the global object). If you create the interpreter in non-strict mode, it will behave as you expect.
