### ISSUE TITLE
MuJS doesn't create the array of user objects

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#77]
I'm trying to use this code to create the array, but it fails:
```
static void createUserArray(js_State *J) {
  js_newarray(J);
  for (int a = 0; a < 100; a++) {
    //js_pushnumber(J, a);
    js_newuserdata(J, TAG, new MyObj(a), nullptr/*no destructor*/);
    js_setindex(J, -2, a);
  }
}
```

In JS, this fails:
```
var a = createUserArray()
print("sz="+a.length)
```
```
TypeError: cannot convert undefined to object
```

It succeeds if ```js_newuserdata``` is replaced with ```js_pushnumber``` above.

**Comment by ccxvii** [comment]
You need to push a prototype object to the stack before the js_newuserdata() call, so that it can set the internal prototype attribute that is used for the userdata object. Typically you will want to use an object that has the methods you want on the userdata type. Hide the object in the registry, or make it a global.

```
static void createUserArray(js_State *J) {
  js_newarray(J);
  for (int a = 0; a < 100; a++) {
    js_pushnull(); // or js_getregistry(TAG) or js_getglobal(TAG)
    js_newuserdata(J, TAG, new MyObj(a), nullptr/*no destructor*/);
    js_setindex(J, -2, a); 
}
```

**Comment by yurivict** [comment]
Adding ```js_pushnull(J);``` doesn't fix the problem, the error is still the same. Same with ```js_getregistry(J, TAG);```

**Comment by yurivict** [comment]
This works, thanks!
