### ISSUE TITLE
Please implement the 'import' statement

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#78]
Without ```import``` it isn't too useful for larger projects.

**Comment by ccxvii** [comment]
`import` is not part of ECMAScript 5. Any such implementation would allow access to the file system, which can allow for unsafe attack vectors. If you want modules, you need to provide the required mechanisms (and make sure they cannot be abused) yourself.

The mujs shell has an example of the `require()` function, using the very common `exports` method, implemented in a few simple lines of code.

**Comment by cup** [comment]
@ccxvii but it is part of ECMAScript 6:

https://developer.mozilla.org/Web/JavaScript/Reference/Statements/import

**Comment by sebras** [comment]
@cup mujs aims to implement ECMAScript 5 as mentioned in the [documentation](https://mujs.com/introduction.html), not ECMAScript 6. The likelihood of this changing is pretty slim, to the best of my knowledge.

**Comment by cup** [comment]
@sebras no worries - I found one that supports ECMAScript 6:

https://bellard.org/quickjs

**Comment by yurivict** [comment]
IMO, MuJS should implement ECMAScript 6. ECMAScript 6 is what people refer now to as JavaScript.

**Comment by sebras** [comment]
mujs was originally implemented to satisfy JavaScript engine requirements for interactive PDF rendering. However @ccxvii saw a benefit in releasing the engine on its own, so that's why we have this mujs project. Even the latest PDF specification, PDF 2.0, refers only to ECMAScript 5.1, which is why there is little incentive to spend time implementing later versions.

**Comment by yurivict** [comment]
You should anticipate that PDF will eventually catch up and switch to ECMAScript 6.
