### ISSUE TITLE
User-defined objects are deleted prematurely, while they are still used in the script

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#81]
How to reproduce:
1. Clone this project: https://github.com/yurivict/ChemWiz
2. Build it: ```make USE_DSRPDB=no```
3. Run the test: ```./chemwiz test-premature-deletion.js```
4. Observe the output:
```
--cycle#164--
--cycle#165--
--cycle#166--
ERROR bogus molecule in moleculeFinalize: 0x801e95000 (duplicate finalize invocation?)
ERROR bogus molecule in moleculeFinalize: 0x801e95000 (duplicate finalize invocation?)
ERROR bogus molecule in moleculeFinalize: 0x801e95000 (duplicate finalize invocation?)
ERROR bogus molecule in moleculeFinalize: 0x801e95000 (duplicate finalize invocation?)
--cycle#167--
Assertion failed: (dbgIsAllocated(this)), function findAaLast, file molecule.cpp, line 125.
Abort trap
```

It runs some operation in a cycle 1000 times. The object ```p``` is used in each iteration, it is created before the cycle. All of a sudden, after the iteration#166, it decides to delete some objects (some of which are also duplicate deletions, see https://github.com/ccxvii/mujs/issues/80).

It also deletes the object ```p``` which is still in use during the cycle, and the assert checking the validity of the object fails.

**Comment by sebras** [comment]
There is no file named `test-premature-deletion.js` in your repository, you probably forgot to add it. (I also looked for branches other than `master`, thinking that you might have a development branch, but there were none.)

**Comment by yurivict** [comment]
I just added it 2 hrs ago, you need to fetch the repository.

**Comment by yurivict** [comment]
https://github.com/yurivict/ChemWiz/blob/master/test-premature-deletion.js

**Comment by sebras** [comment]
I notice that you are throwing C++ exceptions from inside the C++ callbacks that you provide to mujs, e.g. `calcMoleculeEnergy()`. I suspect that this may cause problems with the error handling state in mujs since the exception would circumvent the entire mujs machinery and be handled first at the top level in `main()`. If you do want to use exceptions in your C++ callbacks you need to need to catch those exceptions in the callbacks and upon exception do something suitable in mujs terms, probably calling one of the functions pushing an error object, e.g. `js_error()`.

I made a number of patches for you:
- [fixing a gcc compilation error](https://github.com/sebras/ChemWiz/commit/3e41d258788733469fa437361da647bf3d107686)
- [make it possible to have debug/release versions](https://github.com/sebras/ChemWiz/commit/c189dc0b54644a163e2756e4b98e1bfcb90b885b)
- [LDFLAGS and LDLIBS are not the same thing](https://github.com/sebras/ChemWiz/commit/890d7679b056f257d655e2a86fcd723fe54f4f94)
- [use pkg-config to find mujs](https://github.com/sebras/ChemWiz/commit/5b2751e04488d62f497d7c6a8d79ea4e3017ff67)
- [fix your issue with multiple calls to `moleculeFinalize()`](https://github.com/sebras/ChemWiz/commit/a6d763a8203db8669559133911a42a28f24e6e1e)

In addition to not throwing C++ exceptions your `myimport()` implementation probably ought to be based on the built-in function `require()` where mujs was inspired by [node.js' `require()`](https://nodejs.org/api/modules.html#modules_modules). There is an [example](http://git.ghostscript.com/?p=mujs.git;a=blob;f=main.c;h=68e2c093238b8e9f16030cb9f2e021c97261aaf1;hb=HEAD#l202) in the mujs shell implementation of how this can be implemented. I implemented a [suggestion](https://github.com/sebras/ChemWiz/commit/539dea98bcae707ff0f6a27920a229c09c2077e1), but as noted in the commit message this is a potential security issue hat you might want to fix.

Next time please try to make the example problem as short a possible and only call mujs interface functions. It is rather frustrating to try to find a problem in mujs, only to find it in your software that you ought to be debugging yourself...

With this I close this mujs issue as nothing to be done in mujs.

**Comment by yurivict** [comment]
@sebras Thank you very much for figuring this problem out!
I really appreciate your suggestions! I integrated them all into my project.

Sorry that the problem was in my code, and not in MuJS!

Have a great day!
Yuri

**Comment by sebras** [comment]
@yurivict No worries. I saw that you integrated the changes. You're welcome!
