### ISSUE TITLE
[question] Should there be a js_newscript function that pushes the "function" object to the stack?

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#86]
Similarly to ```js_newcfunction```, one might want to push the JavaScript function to stack. It should be possible to push any type of object, and the function pushing the JavaScript function seems to be missing.

**Comment by ccxvii** [comment]
See: js_loadstring() and js_loadfile().

**Comment by yurivict** [comment]
```js_loadstring``` causes an abort at jsrun.c:1228 without any message.
It also takes the ```filename``` argument. What is supposed to be passed to it when the string is in memory?

**Comment by ccxvii** [comment]
The abort is because it throws and you haven't protected it with js_try. You can also use the js_ploadstring that returns an error code instead of throwing.

The filename argument is used for stack traces and compiler error messages, so set it appropriately. See the implementation of js_dostring for a detailed example.

**Comment by yurivict** [comment]
I passed the nameless function to ```js_ploadstring```:
```js_ploadstring(J, "[string]", "function(m1,m2) {return 1} ")```

The error says:
```SyntaxError: [string]:1: unexpected token: '(' (expected identifier)```

It expects the name? But why?

**Comment by ccxvii** [comment]
It expects a name because that's part of the JS grammar specification. ExpressionStatements cannot be FunctionExpressions, unless you use parenthesis to make a PrimaryExpression grouping operator: `(function(m1,m2){return 1})`.

See https://www.ecma-international.org/ecma-262/5.1/#sec-12.4 for why. At the statement level a "function" keyword is always a FunctionDeclaration, which requires an identifier.

**Comment by yurivict** [comment]
> At the statement level a "function" keyword is always a FunctionDeclaration, which requires an identifier.

So there are two levels: statement level and expression level. At the expression level ```function(m1,m2){return 1}``` should be allowed. Shouldn't there be a twin of ```js_ploadstring``` that interprets the string as an expression?

**Comment by ccxvii** [comment]
No. Why would you even need such a thing?

If you want to create and run an anonymous function as an expression, this is the standard way you see used everywhere: `( function () { print("hello world"); } )();`. This construct is used to keep any variables local to that snippet of code. If they were not wrapped in a function, any "var" declarations would end up creating globals if you were to just run the code.

The reason JS prohibits FunctionExpression in a StatementExpression is because of the syntactic ambiguity between a FunctionExpression and a FunctionDeclaration.

Think of js_loadstring+js_call (or just js_dostring) as the equivalent of doing eval(), without the strange aspects of eval semantics. You cannot pass `function(){}` to eval, nor can you run it in any JS shell or console.

**Comment by ccxvii** [comment]
I suspect you may have misunderstood how js_loadstring works. js_loadstring creates a 'script' object function. The resulting function object runs the script when called. It does not take any arguments.

If you want to create a javascript function object that you can call, with arguments, from C, then you need to create a script that returns a function object.

```
js_pushnull(J); /* this */
js_loadstring(J, "[script]", "return function(m1,m2){return m1+m2;}"); /* load the script */
js_call(J, 0); /* run the script */
```

After this, the function you want is on the top of the stack.

**Comment by ccxvii** [comment]
I suggest you pop onto IRC on freenode.org in the #mupdf channel if you have any further questions.

**Comment by yurivict** [comment]
This solved the problem, thank you for the explanation!
